apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - image: ghcr.io/advplyr/audiobookshelf:2.30.0
          name: audiobookshelf

          envFrom:
            - configMapRef:
                name: audio-configmap
          
          ports:
            - containerPort: 3005
              protocol: TCP

          securityContext:
            fsGroup: 1000
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false

          volumeMounts:
            - mountPath: /config
              name: audio-data
            - mountPath: /metadata
              name: audio-metadata
            - mountPath: /audiobooks
              name: audio-books
            - mountPath: /podcasts
              name: audio-podcasts

      restartPolicy: Always

      volumes:
        - name: audio-data
          persistentVolumeClaim:
            claimName: audio-data-pvc
        - name: audio-metadata
          persistentVolumeClaim:
            claimName: audio-metadata-pvc
        - name: audio-books
          persistentVolumeClaim:
            claimName: audio-books-pvc
        - name: audio-podcasts
          persistentVolumeClaim:
            claimName: audio-podcasts-pvc

